# Generated by Django 3.0.5 on 2020-04-20 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine_app', '0002_auto_20200420_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineapp',
            name='manage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='YourMagazineApp',
        ),
    ]
